include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    - public_member_api_docs
    - prefer_final_locals
    - always_declare_return_types
    - unawaited_futures
    - directives_ordering
    - sort_pub_dependencies
